//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XeroAutomationConsoleApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AppDemo1")]
        public string XeroAppName {
            get {
                return ((string)(this["XeroAppName"]));
            }
            set {
                this["XeroAppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NN2UXHFSN9BKVUJ0VQT6YF31ZNWSHU")]
        public string ConsumerKey {
            get {
                return ((string)(this["ConsumerKey"]));
            }
            set {
                this["ConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AJBXRTVGBZ4YOPRI8QAWBWPYA50RX6")]
        public string ConsumerSecret {
            get {
                return ((string)(this["ConsumerSecret"]));
            }
            set {
                this["ConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.xero.com/oauth/RequestToken")]
        public string RequestTokenURL {
            get {
                return ((string)(this["RequestTokenURL"]));
            }
            set {
                this["RequestTokenURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.xero.com/oauth/Authorize")]
        public string AuthoriseURL {
            get {
                return ((string)(this["AuthoriseURL"]));
            }
            set {
                this["AuthoriseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.xero.com/oauth/AccessToken")]
        public string AccessTokenURL {
            get {
                return ((string)(this["AccessTokenURL"]));
            }
            set {
                this["AccessTokenURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.xero.com/api.xro/2.0/")]
        public string APIEndpointURL {
            get {
                return ((string)(this["APIEndpointURL"]));
            }
            set {
                this["APIEndpointURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string OAuthCallbackDomain {
            get {
                return ((string)(this["OAuthCallbackDomain"]));
            }
            set {
                this["OAuthCallbackDomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.xero.com")]
        public string baseURL {
            get {
                return ((string)(this["baseURL"]));
            }
            set {
                this["baseURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string timeWaitInSeconds {
            get {
                return ((string)(this["timeWaitInSeconds"]));
            }
            set {
                this["timeWaitInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.xero.com/")]
        public string XeroLoginUrl {
            get {
                return ((string)(this["XeroLoginUrl"]));
            }
            set {
                this["XeroLoginUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lolayan@outlook.com")]
        public string XeroUserEmail {
            get {
                return ((string)(this["XeroUserEmail"]));
            }
            set {
                this["XeroUserEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("password123")]
        public string XeroUserPassword {
            get {
                return ((string)(this["XeroUserPassword"]));
            }
            set {
                this["XeroUserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://go.xero.com/Dashboard/")]
        public string XeroDashboardUrl {
            get {
                return ((string)(this["XeroDashboardUrl"]));
            }
            set {
                this["XeroDashboardUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://my.xero.com//Action/OrganisationLogin/!Rbg3D")]
        public string XeroDemoOrgDashboardUrl {
            get {
                return ((string)(this["XeroDemoOrgDashboardUrl"]));
            }
            set {
                this["XeroDemoOrgDashboardUrl"] = value;
            }
        }
    }
}
